[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "10.2.3"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  # Critical for Next.js App Router
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle all routes with Next.js - this is critical for client-side routing to work
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

# Fallback for 404s - redirects to our custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Asset handling - these come after the main handler but won't be used due to force=true above
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Set headers for caching
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
